version: '3.4'

services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    env_file:
      - docker/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    hostname: dbadmin
    ports:
      - 5050:80
    links:
      - db:postgres
    env_file:
      - docker/pgadmin.env
    volumes:
      - db-admin:/var/lib/pgadmin


  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: release
    hostname: django
    container_name: roomusu_django
    restart: always
    command: /wait_for_postgres.sh
    depends_on:
      - db
    env_file:
      - docker/django.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./docker/static:/app/src/static
      - ./docker/media:/app/src/media

  web:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    hostname: roomusu_web
    container_name: roomusu_web
    restart: always
    depends_on:
      - db
      - django
    ports:
      - 3000:80
    volumes:
      - ./docker/static:/static
      - ./docker/media:/media


volumes:
  db-data:
    external: true
  db-admin:
    external: true
