# Generated by Django 3.2 on 2021-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='image',
            field=models.CharField(max_length=255, verbose_name='image'),
        ),
    ]
