# Generated by Django 3.2 on 2021-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feeditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
