# Generated by Django 3.2.1 on 2021-05-05 20:13

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feeditem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='feeditem',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
