# Generated by Django 3.2.1 on 2021-05-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210505_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
