# Generated by Django 3.2.1 on 2021-05-05 23:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_feeditem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': (builtins.id,), 'verbose_name': 'feed item', 'verbose_name_plural': 'feed items'},
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='city'),
        ),
    ]
