# Generated by Django 3.2.1 on 2021-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210506_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='address',
            field=models.TextField(db_index=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
    ]
