# Generated by Django 3.2.1 on 2021-05-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20210506_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'get_latest_by': 'modified', 'ordering': ('pk',), 'verbose_name': 'feed item', 'verbose_name_plural': 'feed items'},
        ),
    ]
